name: Flutter Build
run-name: Build Android App
on: 
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
      - run: echo ${{ secrets.KEYSTORE }} | base64 -d > $GITHUB_WORKSPACE/gesture-calculator.jks
      - run: echo ${{ secrets.KEY_PROPERTIES }} | base64 -d > android/key.properties
      - run: flutter build appbundle
      - run: flutter build apk
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: | 
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/apk/release/app-release.apk
          token: ${{ secrets.PAT }}
      - name: Release To Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: org.seniorlaguna.gcalculator
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production
