name: Flutter Build
run-name: Build Android App
on: 
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
      - run: echo $GITHUB_WORKSPACE
      - run: ls $GITHUB_WORKSPACE
      - name: deserialized secrets
        env:
          KEYSTORE: 
          KEY_PROPERTIES: 
        run: echo ${{ secrets.KEYSTORE }} | base64 -d > $GITHUB_WORKSPACE/gesture-calculator.jks && echo ${{ secrets.KEY_PROPERTIES }} > android/key.properties
      - run: ls $GITHUB_WORKSPACE
      - run: ls $GITHUB_WORKSPACE/android/
      - run: flutter build appbundle
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-debug.apk
